### ISSUE TITLE
Login screen: add a 'Done' button to dismiss keyboard

### ISSUE THREAD

**Issue by oferRounds** [ardaogulcan/react-native-keyboard-accessory#1]
React Native currently does not support [inputAccessoryView](https://developer.apple.com/documentation/uikit/uitextview/1618596-inputaccessoryview) and all the solutions I found to add the bar above the keyboard with the button - don’t really work

**Comment by pburtchaell** [comment]
This could be closed, @oferRounds, because the component currently supports a Done button.

**Comment by oferRounds** [comment]
@pburtchaell cool, thanks! I’ll check it out!
