### ISSUE TITLE
Warning: 'react-native-keyboard-accessory' dependency is not installed.

### ISSUE THREAD

**Issue by teamhide** [ardaogulcan/react-native-keyboard-accessory#11]
When I install with `yarn add react-native-keyboard-accessory`, It throws error 

```
error An unexpected error occurred: "EACCES: permission denied, unlink '/Users/hide/Desktop/username/reactNative/appname/node_modules/.bin/babylon'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/hide/Desktop/username/reactNative/appname/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

So, I tried to install with `sudo yarn add react-native-keyboard-accessory`, 

It seems installed perfectly. But after I launch my application with Expo,
 
Expo throws warngins

```

Warning: 'react-native-keyboard-accessory' dependency is not installed.

If there is an issue running your project, please run `npm install` in /Users/hide/Desktop/username/reactNative/appname and restart.
```

Why is the warning is appears and How can I fix it?

(Since install this package, I have to install every package with sudo. Do you know why?)

**Comment by ardaogulcan** [comment]
When I try `yarn add react-native-keyboard-accessory` with freshly created expo project with `create-react-native-app` it works without an issue. 

And you shouldn't use sudo while installing dependencies for projects. Make sure you have listed all your dependencies in the package.json (and react-native-keyboard accessory is added with version 0.0.8 as `"react-native-keyboard-accessory": "0.0.8"`) and after that can you try to remove your node_modules folder and run `yarn install`
