### ISSUE TITLE
ios app crashes in release mode 

### ISSUE THREAD

**Issue by MorcosS** [ardaogulcan/react-native-keyboard-accessory#13]
app crashes in ios release mode with this exception 
`undefined is not an object (evaluating 'd.View.propTypes.style')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'd.View.prop..., stack:
<unknown>@664:2679
 `
please update View.prop to `(View.propTypes||ViewPropTypes)`
react-native : 0.54.3

**Comment by ardaogulcan** [comment]
Thank you for the Issue and the PR. I'm closing this issue as it is resolved in version [0.0.9](https://github.com/ardaogulcan/react-native-keyboard-accessory/releases/tag/0.0.9)
