### ISSUE TITLE
Keyboard accessory is apart from keyboard, unless the TextInput is in Scrollview

### ISSUE THREAD

**Issue by MorcosS** [ardaogulcan/react-native-keyboard-accessory#15]
Now I am having an issue with the KeyboardNavigation Component, It is always having a space away from the keyboard when the TextInput is not in ScrollView. Although I am adding it to the top view of the component that is having flex:1 as explained in the documentation.
`<View style={{ flex: 1 }} >
                            <View style={styles.flatListView} >
                                <FlatList
                                    keyExtractor={(item, index) => index.toString()}
                                    data={commentsData} renderItem={this.renderComment} refreshControl={<Spinner />}
                                    refreshing={refreshing} onRefresh={() => this.props.refreshCommentsData(postId)}
                                />
                            </View>
                            <View style={styles.commentPostView} >
                                <View style={{
                                    flex: 3, shadowOffset: { width: 1, height: 1 },
                                    shadowColor: 'grey',
                                    shadowOpacity: 0.6,
                                }} >
                                    <TextInput underlineColorAndroid={"transparent"} returnKeyType={'next'} onSubmitEditing={this.postComment} style={styles.commentPost} onChangeText={this.onCommentChanged} autoCorrect={false} placeholder={'Write Comment...'} placeholderTextColor='grey' />
                                </View>
                            </View>
{Platform.OS == 'ios' ?
                    <KeyboardAccessoryNavigation nextDisabled={true}
                        previousDisabled={true}
                        onNext={()=>{}}
                        onPrevious={()=>{}}
                    />
                    :
                    <View />
                }
                    </View>
                }`

What I want to do is to keep the TextInput at the bottom of the screen, so I don't want to add a scrollView.
![simulator screen shot - iphone 6s - 2018-04-23 at 15 33 33](https://user-images.githubusercontent.com/1887089/39130476-71cead60-470d-11e8-81e9-263b698f61fa.png)

I have only solved that by adding a scrollView to the view where the TextInput is found and I don't want to do that.
Any Solution for that?

**Comment by ardaogulcan** [comment]
Please see https://github.com/ardaogulcan/react-native-keyboard-accessory/issues/17

**Comment by saiteja59** [comment]
@ardaogulcan, i really  appreciate your support, actually i am also facing this issue. so i went to #17  i observed your final comment that. i used your refactored cod of @ismailcaferoglu to test this issue.
but still i am facing that issue. i tested my android emulator Nexus 5x, API 27.

<img width="376" alt="screen shot 2018-07-08 at 11 07 01 pm" src="https://user-images.githubusercontent.com/3735048/42422457-e1e38a62-8303-11e8-909e-1fa6828b8bbd.png">

**Comment by ardaogulcan** [comment]
@saiteja59. Thanks for providing extra information. I've reopened issue #17. I will try with the specs you provided and update #17
