### ISSUE TITLE
When i use KeyboardAccessoryView in iPhone X , we are getting more space between keyboard and KeyboardAccessoryView

### ISSUE THREAD

**Issue by saiteja59** [ardaogulcan/react-native-keyboard-accessory#16]
When i use KeyboardAccessoryView in iPhone X , we are getting more space between keyboard and KeyboardAccessoryView, Here we placed KeyboardAccessoryView under SafeAreaView root element.
The purpose of SafeAreaView is to render content within the safe area boundaries of a device
https://facebook.github.io/react-native/docs/safeareaview.html

<img width="330" alt="screen shot 2018-05-22 at 6 18 39 pm" src="https://user-images.githubusercontent.com/3735048/40363376-f1606618-5dec-11e8-9bf8-87b3a4a07975.png">

import React, { Component } from 'react';

import {
  StyleSheet,
  View,
  TextInput,
  Button,
  ScrollView,
SafeAreaView
} from 'react-native';

import { KeyboardAccessoryView } from '../react-native-keyboard-accessory';

class ViewExample extends Component {
  render() {
    return (
      <SafeAreaView style={styles.container}>
        <ScrollView>
          <Button title="Go to Navigation Example" onPress={() => {
            this.props.navigation.navigate('NavigationView')
          }} />
        </ScrollView>
        <KeyboardAccessoryView alwaysVisible={true}>
          <View style={styles.textInputView}>
            <TextInput
              underlineColorAndroid="transparent"
              style={styles.textInput}
              multiline={true} />
            <Button
              style={styles.textInputButton}
              title="Send"
              onPress={() => {}}/>
          </View>
        </KeyboardAccessoryView>
      </SafeAreaView>
    );
  }
}
ViewExample.navigationOptions = {
  title: 'View Example',
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  textInputView: {
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textInput: {
    flexGrow: 1,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#CCC',
    padding: 10,
    fontSize: 16,
    marginRight: 10,
    textAlignVertical: 'top'
  },
  textInputButton: {
    flexShrink: 1,
  }
});

export default ViewExample;

**Comment by ardaogulcan** [comment]
Hi thank you for noticing the issue. 

With https://github.com/ardaogulcan/react-native-keyboard-accessory/commit/7e54b868f276df3f3dff0f0cd9610f47743474ab I've added the `inSafeAreaView` prop which can be used like;
```js
<SafeAreaView>
...
<KeyboardAccessoryView inSafeAreaView>
  ...
</KeyboardAccessoryView>
...
</SafeAreaView>
```

It should be available on [v0.0.11](https://github.com/ardaogulcan/react-native-keyboard-accessory/releases/tag/0.0.11)
