### ISSUE TITLE
Requires "React Navigation" module

### ISSUE THREAD

**Issue by saxs4x** [ardaogulcan/react-native-keyboard-accessory#18]
I get an error that says: Failed to load bundle, cause Module 'react-navigation' does not exist in the haste module map.

**Comment by ardaogulcan** [comment]
This error is not related to `react-native-keyboard-accessory` as it doesn't depend on on `react-navigation`. You probably need to reset your bundler cache. Please try
```cli
npm run react-native start --reset-cache
```

**Comment by utkusubakan** [comment]
@ardaogulcan please remove

`import { TabBarBottom } from 'react-navigation'`

line from KeyboardAwareTabBarComponent.js 

https://github.com/ardaogulcan/react-native-keyboard-accessory/blob/master/lib/KeyboardAwareTabBarComponent.js

**Comment by ardaogulcan** [comment]
Hi @utkusubakan thanks for noticing that. With the [v0.1.1](https://github.com/ardaogulcan/react-native-keyboard-accessory/releases/tag/0.1.1) `react-navigation` is no longer a dependency.
