### ISSUE TITLE
Using RN's inputAccessoryView for native iOS?

### ISSUE THREAD

**Issue by fungilation** [ardaogulcan/react-native-keyboard-accessory#19]
* https://facebook.github.io/react-native/blog/2018/03/22/building-input-accessory-view-for-react-native.html
* https://facebook.github.io/react-native/docs/inputaccessoryview.html

Has anyone looked at moving the iOS side of this component to use RN's own, since 0.55? It's built to use the native iOS component to ensure stickiness. That is however iOS only, and this component supports both iOS and Android. Would be great to get the best of both worlds.

**Comment by utkusubakan** [comment]
I have tested but there are some problems like this:
https://github.com/facebook/react-native/issues/18997

**Comment by fungilation** [comment]
That's quite bad. RN 0.56 just released, not sure if it fixed this.

**Comment by ardaogulcan** [comment]
Hi @fungilation,

I was also thinking about that but there are still some issues with RN InputAccessoryView. As @utkusubakan mentioned there is height problem. Also there were import problems https://github.com/facebook/react-native/issues/18923 till the last release. Which is still not coming with create-react-native-app. When all this issues solved i will try to implement native version to library.
