### ISSUE TITLE
Extra space appears at top of view after using keyboardAccessoryNavigation

### ISSUE THREAD

**Issue by clfristoe** [ardaogulcan/react-native-keyboard-accessory#24]
When I tap the next or previous buttons, it scrolls as expected but when I tap the Done button or tap outside the keyboard, extra space appears at the top of the View (see video in zip file):
[ExtraSpace.zip](https://github.com/ardaogulcan/react-native-keyboard-accessory/files/2361793/ExtraSpace.zip)

The code:
`<ScreenRoot {...getCommonProps(this.props)} navigator={this.props.navigator} showFormNav={false} avoidKeyboard={false}>`
`<KeyboardScrollView>`
						`<Form
							form={formName}
							ref={this.saveForm}
							onSubmit={this.handleSubmit}
							validate={validate}
							initialValues={this.initialValues}
						>`
							`{this.props.currentUser.showDigitalDials === 'Yes' &&
							<FormPicker title={'Contact Method'} name={'actualContactMethod'} items={actualContactMethodItems}/>}`
							`<FormSwitch
								title={'New Set?'}
								name={'isNewSetCode'}
							/>`
							`<FormSwitch
								title={'Create Appointment?'}
								name={'createAppointment'}
							/>`
							`{appointmentComponents}`
						`</Form>`
					`</KeyboardScrollView>`
					`<KeyboardAccessoryNavigation/>`
				`</ScreenRoot>`

**Comment by clfristoe** [comment]
I just downloaded the example project and can confirm that this also occurs when there are seven fields on the same page. https://snack.expo.io/rJG0LIl_Q

To reproduce:
tap on the last field in the list, tap Done, and notice the extra space at the top of the view above the hide arrows toggle

**Comment by ardaogulcan** [comment]
Hey @clfristoe, this is actually about `KeyboardAwareScrollView` you need to set `enableResetScrollToCoords` prop to `false`. For Example;

```javascript
<View style={{ flex: 1 }}>
  <KeyboardAwareScrollView
    ...
    enableResetScrollToCoords={false}>
...
```javascript

**Comment by clfristoe** [comment]
@ardaogulcan thank you so much for the quick reply! Solved the issue.
