### ISSUE TITLE
Combining KeyboardAccessoryView with TextInput

### ISSUE THREAD

**Issue by kdawgwilk** [ardaogulcan/react-native-keyboard-accessory#26]
How would I go about creating a KeyboardAccessoryView that only shows up when a TextInput (not nested inside the KeyboardAccessoryView) has been selected and the keyboard is displayed.  similar to how the RN `InputAccessoryView` works by attaching a reference by id on the TextInput that activates the accessory view

**Comment by ardaogulcan** [comment]
Hey @kdawgwilk, It is the default behaviour of `AccessoryView` you need to set height for the inner view though.  Please check the this snack: https://snack.expo.io/@ardaogulcan/anxious-croissant
