### ISSUE TITLE
[Android] KeyboardAccessoryView can not set backgroundColor to transparent

### ISSUE THREAD

**Issue by Jrafalak** [ardaogulcan/react-native-keyboard-accessory#40]
I'm trying to use the KeyboardAccessoryView to create a row of 'floating' buttons above the keyboard. On iOS I can set the background of the view to transparent and that style is respected. However, for Android, the background of the view is just white and I cannot make it transparent. Even if the width of the view is only 50% of the screen, the rest of the width of the screen is white.

**Comment by ardaogulcan** [comment]
Hi @Jrafalak can you create an example for your case from https://snack.expo.io/@ardaogulcan/react-native-keyboard-accessory-playground

**Comment by Jrafalak** [comment]
Hey @ardaogulcan , I created an example but I did not have the same issue on snack. The Android keyboard view went transparent just fine. I can't see what I'm doing differently at this point in my codebase, but if this isn't a common issue you've seen, maybe I'll need to dig deeper into what may be happening.
