### ISSUE TITLE
<KeyboardAccessoryNavigation> is not working inside a scrollview

### ISSUE THREAD

**Issue by arunkrishnang86** [ardaogulcan/react-native-keyboard-accessory#41]
onDone is not working when we use <KeyboardAccessoryNavigation> in the inner views or scroll views.

**Comment by ardaogulcan** [comment]
Hi @arunkrishnang86 can you create an example for your case from https://snack.expo.io/@ardaogulcan/react-native-keyboard-accessory-playground

**Comment by arunkrishnang86** [comment]
<View style={{ flex: 1 }}>
      <ScrollView>
           <View>
             <REPORT/>
          </View>
        </ScrollView>
</View>

REPORT component is 

<View>
       <View>
        <TextInput
          multiline={true}
          keyboardType="default"
          blurOnSubmit={false}
        />
        </View>
         <KeyboardAccessoryNavigation
          avoidKeyboard={true}
          multiline={true}
          androidAdjustResize ={true}
          onDone={this.onDone}
        />
 </View>

onDone is not working and how to align accessory view above the keyboard not affecting the scroll view?
Inside the scrollview there are many views , <REPORT/> i am using this <KeyboardAccessoryNavigation/>

**Comment by emilfrolov** [comment]
I have the same issue 😞onDone does not work recently

**Comment by ardaogulcan** [comment]
@arunkrishnang86 and @emilfrolov issue you are facing is not related to onDone of KeyboardAccessory but rather related to positioning issue which causes onDone (or other elements of accessory) to be not accessible for press. You need to fix how you positioned the accessory. And is it is suggested on Readme KeyboardAccessory should be positioned inside the top View which has  style flex: 1. 

For example @arunkrishnang86 issue can be easily fixed by moving KeyboardAccessoryNavigation out of REPORT component to top View

```js
<View style={{ flex: 1 }}>
  <ScrollView>
    <View>
      <REPORT/>
    </View>
  </ScrollView>
  <KeyboardAccessoryNavigation
     avoidKeyboard={true}
     multiline={true}
     androidAdjustResize ={true}
     onDone={this.onDone}
  />
</View>
```

https://snack.expo.io/r1y9a4u6E

**Comment by shivani805** [comment]
In my case KeyboardAccessoryNavigation not following the keyboard 

  <Backdrop contentContainerStyle={styles.container}>
      <View>
        <TextInput placeholder="email" />
        <TextInput placeholder="password" />
      </View>

      <KeyboardAccessoryNavigation
        nextDisabled={inputState.nextFocusDisabled}
        previousDisabled={inputState.previousFocusDisabled}
        onNext={() => handleFocusNext(inputState, inputs)}
        onPrevious={() => handleFocusPrevious(inputState, inputs)}
        multiline
        avoidKeyboard
        androidAdjustResize
      />
    </Backdrop>
