### ISSUE TITLE
Android is not registering onPress events

### ISSUE THREAD

**Issue by bsbechtel** [ardaogulcan/react-native-keyboard-accessory#46]
In the Android emulator, I am not getting the KeyboardAccessoryView to fire any touch events. I wrapped the entire view in a TouchableOpacity component, and the onPress handler does not ever fire. Is it possible this is just the behavior in the emulator?

```
      <TouchableOpacity onPress={() => console.log('pressed!')}>
      <View style={{ height: (isKeyboardVisible || alwaysVisible ? visibleHeight  : 0) }}>
        <View
          style={[
            styles.accessory,
            !hideBorder && styles.accessoryBorder,
            style,
            {
              opacity: (isKeyboardVisible || alwaysVisible ? visibleOpacity : hiddenOpacity),
              bottom: keyboardHeight - bumperHeight - (applySafeArea ? 0 : 0),
              height: accessoryHeight + bumperHeight + (applySafeArea ? (isKeyboardVisible ? 0 : 20) : 0),
              backgroundColor: KomplishTheme.primaryColor,
            }
          ]}
        >
          <View onLayout={this.handleChildrenLayout}>
            { this.props.children }
          </View>
        </View>
      </View>
      </TouchableOpacity>
```
<img width="301" alt="Screen Shot 2020-01-24 at 7 21 43 AM" src="https://user-images.githubusercontent.com/1334933/73068894-56b73180-3e7a-11ea-89eb-46f231f4f50c.png">

**Comment by Dannybevers** [comment]
Got the same issue, any solution already?

**Comment by bsbechtel** [comment]
It was a while back, but I believe it ended up being an issue with absolute positioning.

**Comment by Seanmclem** [comment]
> It was a while back, but I believe it ended up being an issue with absolute positioning.

same, I had to remove absolute position references on the component and it worked immediately. position absolute seemed to cause touch events to pass right through
