### ISSUE TITLE
[Feature Suggestion] Add hitSlop to prop for AccessoryNavigations buttons

### ISSUE THREAD

**Issue by jong-hui** [ardaogulcan/react-native-keyboard-accessory#53]
Hello!
thanks for this great library!

Today's buttons(previous, next, done) have a small touchable area. It is difficult to press.
So I want to add hitSlop to prop.

**Comment by ardaogulcan** [comment]
This change is included in [v0.1.13](https://github.com/ardaogulcan/react-native-keyboard-accessory/releases/tag/0.1.13). #54, Thanks @jong-hui for the contribution.
