### ISSUE TITLE
Update React Versions

### ISSUE THREAD

**Issue by pburtchaell** [ardaogulcan/react-native-keyboard-accessory#7]
The library currently lists the alpha version of React as a peer dependency.

https://github.com/ardaogulcan/react-native-keyboard-accessory/blob/9260ebf51e18162a0171a64acdbdbb523ddf2095/package.json#L40-L41

Can you update to React `16.x` and a higher React Native version?

**Comment by pburtchaell** [comment]
I'm happy to make a PR if needed.

**Comment by ardaogulcan** [comment]
Hi @pburtchaell I have updated the dependencies and fix the example.
