### ISSUE TITLE
Should the input accessory always have a border

### ISSUE THREAD

**Issue by pburtchaell** [ardaogulcan/react-native-keyboard-accessory#9]
From what I can tell, based off Apple documentation, from reading articles on the Input Accessory view, and from using apps, there's a border on top of the input accessory. 

I've noticed you included a border in one of the examples:

https://github.com/ardaogulcan/react-native-keyboard-accessory/blob/9b02f55534d96018bc05ffbfad9406470dbe0adb/example/screens/NavigationViewExample.js#L90-L92

But this border is not included in the component itself. Is there a particular reason why?

**Comment by ardaogulcan** [comment]
Actually, when I first wrote the library it was necessary for one of my projects and the design was created borderless therefore I didn't put border to the accessory as it can be easily added by the style when needed. 

However, as you have told it is common to have a border on Input Accessory View on iOS. Maybe we can add default border which can be disabled by props.

**Comment by pburtchaell** [comment]
Gotcha! Yeah, I think it makes sense to have the border and maybe a `disableBorder` prop?

**Comment by ardaogulcan** [comment]
I added the default border and `hideBorder` prop to hide it at this commit https://github.com/ardaogulcan/react-native-keyboard-accessory/commit/7a29bfc74bc6d2a1f2e454491a69b021c86baca8

@pburtchaell  Thank you for noticing this.
